// examples/svelte/app/components/ui/ListPicker.svelte

<page>
    <actionBar >
      <label>ListPicker</label>
    </actionBar>

    <gridLayout>
      <contentView
        horizontalAlignment="center"
        verticalAlignment="center">
        <!--      region example -->
        <listPicker items="{items}"></listPicker>
        <!--      endregion example-->
      </contentView>
    </gridLayout>
</page>

<script lang="ts">
  const items = ['First','Second','Third']
</script>

<style>
</style>

// examples/solidJs/src/ui/listpicker.tsx
import { Frame } from '@nativescript/core'

export const ListPicker = () => {

  const choices = [
    "First",
    "Second",
    "Third"
  ];
  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="ListPicker">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <listpicker items={choices}></listpicker>
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};
