// examples/svelte/app/components/ui/TextField.svelte
<script lang="ts">
</script>

<page>
  <actionBar>
    <label>TextField</label>
  </actionBar>

  <gridLayout width="100%">
    <contentView verticalAlignment="center">
      <!-- #region example -->
      <textField hint="Placeholder..." />
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>

// examples/solidJs/src/ui/textfield.tsx
import { Frame } from '@nativescript/core'

export const TextField = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="ActionBar">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};
