// examples/svelte/app/components/Home.svelte
<page>
    <actionBar >
      <label text="Home"
             class="font-bold text-lg" />
    </actionBar>
    <gridLayout>
      <listView items="{examples}" on:itemTap="{goTo}">
          <Template let:item>
            <label class="item-label" text="{item.name}" padding="16" color="black" borderBottomColor="black"></label>
          </Template>
      </listView>
    </gridLayout>
</page>

<script lang="ts">
  import { Template } from 'svelte-native/components'
  import Button from '~/components/ui/Button.svelte'
  import { navigate } from 'svelte-native'
  import ActivityIndicator from '~/components/ui/ActivityIndicator.svelte'
  import ActionBar from '~/components/ui/ActionBar.svelte'
  import DatePicker from '~/components/ui/DatePicker.svelte'
  import Dialogs from '~/components/ui/Dialogs.svelte'
  import HtmlView from '~/components/ui/HtmlView.svelte'
  import Image from '~/components/ui/Image.svelte'
  import Label from '~/components/ui/Label.svelte'
  import ListPicker from '~/components/ui/ListPicker.svelte'
  import ListView from '~/components/ui/ListView.svelte'
  import Placeholder from '~/components/ui/Placeholder.svelte'
  import Progress from '~/components/ui/Progress.svelte'
  import ScrollView from '~/components/ui/ScrollView.svelte'
  import Searchbar from '~/components/ui/SearchBar.svelte'
  import SegmentedBar from '~/components/ui/SegmentedBar.svelte'
  import Slider from '~/components/ui/Slider.svelte'
  import Switch from '~/components/ui/Switch.svelte'
  import TabView from '~/components/ui/TabView.svelte'
  import TextField from '~/components/ui/TextField.svelte'
  import TextView from '~/components/ui/TextView.svelte'
  import TimePicker from '~/components/ui/TimePicker.svelte'
  import WebView from '~/components/ui/WebView.svelte'

  const examples = [
    {name: 'ActionBar', component: ActionBar},
    {name: 'ActivityIndicator', component: ActivityIndicator},
    {name: 'Button', component: Button},
    {name: 'DatePicker', component: DatePicker},
    {name: 'Dialogs', component: Dialogs},
    {name: 'HtmlView', component: HtmlView},
    {name: 'Image', component: Image},
    {name: 'Label', component: Label},
    {name: 'ListPicker', component: ListPicker},
    {name: 'ListView', component: ListView},
    {name: 'Placeholder', component: Placeholder},
    {name: 'Progress', component: Progress},
    {name: 'ScrollView', component: ScrollView},
    {name: 'SearchBar', component: Searchbar},
    {name: 'SegmentedBar', component: SegmentedBar},
    {name: 'Slider', component: Slider},
    {name: 'Switch', component: Switch},
    {name: 'TabView', component: TabView},
    {name: 'TextField', component: TextField},
    {name: 'TextView', component: TextView},
    {name: 'TimePicker', component: TimePicker},
    {name: 'WebView', component: WebView},

  ]

  function goTo(args) {
    const {index} = args;
    console.log(index);
    const item = examples[index];
    switch (item.name) {
      case 'ActionBar':
        navigate({ page: ActionBar })
        break
      case 'ActivityIndicator':
        navigate({ page: ActivityIndicator })
        break
      case 'Button':
        navigate({ page: Button })
        break
      case 'DatePicker':
        navigate({ page: DatePicker })
        break
      case 'Dialogs':
        navigate({ page: Dialogs })
        break
      case 'HtmlView':
        navigate({ page: HtmlView })
        break
      case 'Image':
        navigate({ page: Image })
        break
      case 'Label':
        navigate({ page: Label })
        break
      case 'ListPicker':
        navigate({ page: ListPicker })
        break
      case 'ListView':
        navigate({ page: ListView })
        break
      case 'Placeholder':
        navigate({ page: Placeholder })
        break
      case 'Progress':
        navigate({ page: Progress })
        break
      case 'ScrollView':
        navigate({ page: ScrollView })
        break
      case 'SearchBar':
        navigate({ page: Searchbar })
        break
      case 'SegmentedBar':
        navigate({ page: SegmentedBar })
        break
      case 'Slider':
        navigate({ page: Slider })
        break
      case 'Switch':
        navigate({ page: Switch })
        break
      case 'TabView':
        navigate({ page: TabView })
        break
      case 'TextField':
        navigate({ page: TextField })
        break
      case 'TextView':
        navigate({ page: TextView })
        break
      case 'TimePicker':
        navigate({ page: TimePicker })
        break
      case 'WebView':
        navigate({ page: WebView })
        break
      default:
        break
    }
  }
</script>

<style>
  .item-label{
  }
</style>

// examples/vue/src/Home.vue
<script lang="ts" setup>
import { ref, $navigateTo } from 'nativescript-vue'

import { getComponentList } from '@example/utils'
import Actionbar from './ui/Actionbar/component.vue'
import ActivityIndicator from './ui/ActivityIndicator/component.vue'
import Button from './ui/Button/component.vue'
import DatePicker from './ui/DatePicker/component.vue'
import Dialogs from './ui/Dialogs/component.vue'
import HtmlView from './ui/HtmlView/component.vue'
import Image from './ui/Image/component.vue'
import Label_  from './ui/Label_/component.vue'
import ListPicker from './ui/ListPicker/component.vue'
import Listview  from './ui/Listview/component.vue'
import Placeholder from './ui/Placeholder/component.vue'
import Progress from './ui/Progress/component.vue'
import ScrollView from './ui/ScrollView/component.vue'
import SearchBar from './ui/SearchBar/component.vue'
import SegmentedBar from './ui/SegmentedBar/component.vue'
import Slider from './ui/Slider/component.vue'
import Switch from './ui/Switch/component.vue'
import TabView from './ui/TabView/component.vue'
import TextField from './ui/TextField/component.vue'
import TextView from './ui/TextView/component.vue'
import TimePicker from './ui/TimePicker/component.vue'
import WebView from './ui/WebView/component.vue'
const examples = ref<Array<{ name: string }>>(
  getComponentList(
    // @ts-expect-error
    require.context('./ui/', true, /component\.vue$/),
    '/component.vue'
  )
)

const goTo = (args: any) => {
  const { index } = args
  console.log(examples);
  const item = examples.value[index]
  console.log('item:', item)
  switch (item.name) {
    case 'Actionbar':
      $navigateTo(Actionbar)
      break
    case 'ActivityIndicator':
      $navigateTo(ActivityIndicator)
      break
    case 'Button':
      $navigateTo(Button)
      break
    case 'DatePicker':
      $navigateTo(DatePicker)
      break
    case 'Dialogs':
      $navigateTo(Dialogs)
      break
    case 'HtmlView':
      $navigateTo(HtmlView)
      break
    case 'Image':
      $navigateTo(Image)
      break
    case 'Label_':
      $navigateTo(Label_)
      break
    case 'ListPicker':
      $navigateTo(ListPicker)
      break
    case 'Listview':
      $navigateTo(Listview)
      break
    case 'Placeholder':
      $navigateTo(Placeholder)
      break
    case 'Progress':
      $navigateTo(Progress)
      break
    case 'ScrollView':
      $navigateTo(ScrollView)
      break
    case 'SearchBar':
      $navigateTo(SearchBar)
      break
    case 'SegmentedBar':
      $navigateTo(SegmentedBar)
      break
    case 'Slider':
      $navigateTo(Slider)
      break
    case 'Switch':
      $navigateTo(Switch)
      break
    case 'TabView':
      $navigateTo(TabView)
      break
    case 'TextField':
      $navigateTo(TextField)
      break
    case 'TextView':
      $navigateTo(TextView)
      break
    case 'TimePicker':
      $navigateTo(TimePicker)
      break
    case 'WebView':
      $navigateTo(WebView)
      break
    default:
      console.log('No component found')
      break
  }
}
</script>

<template>
  <Frame>
    <Page>
      <ActionBar>
        <Label text="Home" class="font-bold text-lg" />
      </ActionBar>

      <GridLayout>
        <ListView :items="examples" @itemTap="goTo">
          <template #default="{ item }">
            <StackLayout>
              <Label :text="item.name" padding="16" color="black" />
            </StackLayout>
          </template>
        </ListView>
      </GridLayout>
    </Page>
  </Frame>
</template>
