// examples/svelte/app/components/ui/HtmlView.svelte

<page>
    <actionBar >
      <label>HTML View</label>
    </actionBar>

    <gridLayout>
      <contentView
        horizontalAlignment="center"
        verticalAlignment="center">
<!--        region example-->
        <htmlView html="{htmlString}"></htmlView>
<!--        endregion example-->
      </contentView>
    </gridLayout>
</page>

<script lang="ts">
  const htmlString = `
    <h1 style="color: black; font-family: ui-sans-serif, system-ui;">
      <span style="color: #65adf1;">Html</span>View
    </h1>
    `
</script>

<style>
</style>

// examples/react/src/components/ui/htmlview.tsx
import { Dialogs, Frame } from '@nativescript/core'
import { RouteProp } from '@react-navigation/core';
import * as React from "react";
import { StyleSheet } from "react-nativescript";
import { FrameNavigationProp } from "react-nativescript-navigation";

import { MainStackParamList } from '../../NavigationParamList'

type HomeProps = {
    route: RouteProp<MainStackParamList, "HtmlView">,
    navigation: FrameNavigationProp<MainStackParamList, "HtmlView">,
};

export function HtmlView({ navigation }: HomeProps) {

  // todo not working color
  const htmlString = `
   <h1 style="color: black; font-family: ui-sans-serif, system-ui;">
      <span style="color: #65adf1;">Html</span>View
    </h1>
    `
    return (
      <>
        <frame>
          <page style={styles.container}>
            <actionBar
              title="HtmlView"
              onTap={() => Frame.goBack()}
            ></actionBar>

            <stackLayout
              verticalAlignment={'middle'}
              horizontalAlignment={'center'}
            >
              {/*#region example*/}

              <htmlView html={htmlString}></htmlView>
              {/*endregion example*/}
            </stackLayout>
          </page>
        </frame>
      </>
    )
}

const styles = StyleSheet.create({
  container: {
    height: "100%",
    flexDirection: "column",
    justifyContent: "center",
  },
  text: {
    textAlignment: "center",
    fontSize: 24,
    color: "black",
  },
  button: {
    fontSize: 24,
    color: "#2e6ddf",
  },
});
