// examples/svelte/app/components/ui/ActionBar.svelte

<page>
  <!--        #region example-->
    <actionBar >
      <actionItem on:tap={goBack()}>
        <label text="<< Back"></label>
      </actionItem>
    </actionBar>
  <!--        #endregion example-->

    <gridLayout>
      <contentView verticalAlignment="center">

        <label text="Main Content"
        verticalAlignment="center"
        horizontalAlignment="center"></label>
      </contentView>
    </gridLayout>
</page>

<script lang="ts">
  import { Frame } from '@nativescript/core'

  function goBack() {
    Frame.goBack();

  }
</script>

<style>
</style>

// examples/solid/src/ui/actionbar.tsx

{/* #region example */}
import { Frame } from '@nativescript/core'

export const ActionBar = () => {
  function goBack() {
    Frame.goBack()
  }

  return (<>
    <actionbar title="ActionBar">
      <actionitem on:tap={goBack} text="<<Back"></actionitem>
    </actionbar>
    <gridlayout>
      <label>Main Content</label>
    </gridlayout>
  </>)
}
{/* #endregion example */}
