// examples/svelte/app/components/ui/HtmlView.svelte

<page>
    <actionBar >
      <label>HTML View</label>
    </actionBar>

    <gridLayout>
      <contentView
        horizontalAlignment="center"
        verticalAlignment="center">
<!--        region example-->
        <htmlView html="{htmlString}"></htmlView>
<!--        endregion example-->
      </contentView>
    </gridLayout>
</page>

<script lang="ts">
  const htmlString = `
    <h1 style="color: black; font-family: ui-sans-serif, system-ui;">
      <span style="color: #65adf1;">Html</span>View
    </h1>
    `
</script>

<style>
</style>

// examples/solid/src/ui/htmlview.tsx
import { Frame } from '@nativescript/core'

export const HtmlView = () => {
  const htmlString = `
    <h1 style="color: black; font-family: ui-sans-serif, system-ui;">
      <span style="color: #65adf1;">Html</span>View
    </h1>
  `
  function goBack() {
    Frame.goBack()
  }
  return (
    <>
      <actionbar title="HtmlView">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout
        ios:visibility="collapse"
        verticalAlignment="center"
        horizontalAlignment="center"
      >
        {/* #region example */}
        <htmlview html={htmlString}></htmlview>
        {/* #endregion example */}
      </gridlayout>
    </>
  )
}
