// examples/svelte/app/components/ui/Label.svelte
<script lang="ts">
</script>

<page>
  <actionBar>
    <label>Label</label>
  </actionBar>

  <gridLayout>
    <contentView horizontalAlignment="center" verticalAlignment="center">
      <!-- #region example -->
      <label text="Hello NativeScript"></label>
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>

// examples/solid/src/ui/label.tsx
import { Frame } from '@nativescript/core'

export const Label = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="Label">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <label text='TextHere'/>
        {/*#endregion example*/}

      </gridlayout>
    </>
  );
};
