// examples/solidJs/src/ui/switch.tsx
import { Frame } from '@nativescript/core'

export const Switch = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="ActionBar">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};

// examples/solid/src/ui/switch.tsx
import { Frame } from '@nativescript/core'
import { createSignal } from 'solid-js'

export const Switch = () => {
  const [switchValue, setSwitchValue] = createSignal(true)

  const handleChange = (event: Event) => {
    setSwitchValue(event.value)
    console.log(event.value)
  }
  function goBack() {
    Frame.goBack()
  }
  return (
    <>
      <actionbar title="Switch">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout
        ios:visibility="collapse"
        verticalAlignment="center"
        horizontalAlignment="center"
      >
        {/* #region example */}
          <switch
            on:checkedChange={handleChange}
            checked={switchValue()}
          ></switch>
        {/* #endregion example */}
      </gridlayout>
    </>
  )
}
