// examples/svelte/app/components/ui/Switch.svelte

<page>
    <actionBar >
      <label>Switch</label>
    </actionBar>

  <gridLayout width="100%">
    <contentView
      width="100%"
      horizontalAlignment="center"
      verticalAlignment="center">
      <!--      region example -->
     <stackLayout>
       <switch horizontalAlignment="center" bind:checked="{switchValue}"></switch>
       <label textAlignment="center" width="100%">{switchValue}</label>
     </stackLayout>
      <!--      endregion example-->
    </contentView>
  </gridLayout>
</page>

<script lang="ts">
  let switchValue = true;
</script>

<style>
</style>

// examples/solid/src/ui/switch.tsx
import { Frame } from '@nativescript/core'
import { createSignal } from 'solid-js'

export const Switch = () => {
  const [switchValue, setSwitchValue] = createSignal(true)

  const handleChange = (event: Event) => {
    setSwitchValue(event.value)
    console.log(event.value)
  }
  function goBack() {
    Frame.goBack()
  }
  return (
    <>
      <actionbar title="Switch">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout
        ios:visibility="collapse"
        verticalAlignment="center"
        horizontalAlignment="center"
      >
        {/* #region example */}
        <stacklayout>
          <switch
            horizontalAlignment="center"
            on:checkedChange={handleChange}
            checked={switchValue()}
          ></switch>
        </stacklayout>
        {/* #endregion example */}
      </gridlayout>
    </>
  )
}
