// examples/svelte/app/components/ui/TextView.svelte
<script lang="ts">
  const text = `TextView\nWith\nMultiple\nLines!`
</script>

<page>
  <actionBar>
    <label>TextView</label>
  </actionBar>

  <gridLayout width="100%">
    <contentView
      width="100%"
      horizontalAlignment="center"
      verticalAlignment="center"
    >
      <!-- #region example -->
      <textView {text} />
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>

// examples/solid/src/ui/textview.tsx
import { Frame } from '@nativescript/core'

export const TextView = () => {

  // #region example
  const text = `TextView\nWith\nMultiple\nLines!`;
  // #endregion example
  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="TextView">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <textview text={text} />
        {/*#endregion example*/}

      </gridlayout>
    </>
  );
};
