// examples/svelte/app/components/ui/TimePicker.svelte
<script lang="ts">
</script>

<page>
  <actionBar>
    <label>TimePicker</label>
  </actionBar>

  <gridLayout width="100%">
    <contentView verticalAlignment="center" horizontalAlignment="center">
      <timePicker hour="9" minute="41" />
    </contentView>

    <contentView visibility="collapsed">
      <!-- #region example -->
      <timePicker />
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>

// examples/solid/src/ui/timepicker.tsx
import { Frame } from '@nativescript/core'

export const TimePicker = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="TimePicker">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <timepicker hour="9" minute="41" />
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};
