// examples/react/src/components/ui/actionbar.tsx
import { Dialogs, Frame } from '@nativescript/core'
import { RouteProp } from '@react-navigation/core'
import * as React from 'react'
import { StyleSheet } from 'react-nativescript'
import { FrameNavigationProp } from 'react-nativescript-navigation'
import { MainStackParamList } from '../../NavigationParamList'

type HomeProps = {
  route: RouteProp<MainStackParamList, 'ActionBar'>
  navigation: FrameNavigationProp<MainStackParamList, 'ActionBar'>
}

export function ActionBar({ navigation }: HomeProps) {
  return (
    <>
      <frame>
        <page style={styles.container}>
          {/* #region example */}
          <actionBar title="ActionBar" onTap={() => Frame.goBack()}></actionBar>
          {/* #endregion example */}

          <stackLayout
            verticalAlignment={'middle'}
            horizontalAlignment={'center'}
          >
            <label text="ActionBar" />
          </stackLayout>
        </page>
      </frame>
    </>
  )
}

const styles = StyleSheet.create({
  container: {
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  text: {
    textAlignment: 'center',
    fontSize: 24,
    color: 'black',
  },
  button: {
    fontSize: 24,
    color: '#2e6ddf',
  },
})

// examples/svelte/app/components/ui/ActionBar.svelte
<script lang="ts">
  import { Frame } from '@nativescript/core'

  function goBack() {
    Frame.goBack()
  }
</script>

<page>
  <!-- #region example-->

  <actionBar title="ActionBar">
    <actionItem on:tap={goBack}>
      <label text="<< Back" class="font-bold text-lg" />
    </actionItem>
  </actionBar>
  <!-- #endregion example-->

  <gridLayout>
    <contentView horizontalAlignment="center" verticalAlignment="center">
      <label>Main Content</label>
    </contentView>
  </gridLayout>
</page>

<style>
</style>
