// examples/solid/src/ui/activityindicator.tsx
import { Frame } from '@nativescript/core'

export const ActivityIndicator = () => {
  function goBack() {
    Frame.goBack()
  }
  return (
    <>
      <actionbar title="ActionBar">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout>
        <contentview
          verticalAlignment="center"
          horizontalAlignment="center"
          android:visibility="collapse"
        >
          {/* #region example */}
          <activityindicator busy="true" />
          {/* #endregion example */}
        </contentview>

        <gridlayout
          ios:visibility="collapse"
          verticalAlignment="center"
          horizontalAlignment="center"
        >
          <contentview
            width="40"
            height="40"
            borderRadius="50"
            borderWidth="4"
            borderColor="#65adf1"
          />
          <contentview
            width="40"
            height="40"
            translateX="-20"
            translateY="-20"
            backgroundColor="white"
          />
        </gridlayout>
      </gridlayout>
    </>
  )
}

// examples/svelte/app/components/ui/ActivityIndicator.svelte
<script lang="ts">
</script>

<page>
  <actionBar>
    <label text="ActivityIndicator" class="font-bold text-lg" />
  </actionBar>
  <gridLayout>
    <contentView verticalAlignment="center">
      <!-- #region example -->
      <activityIndicator busy="true" />
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>
