// examples/solid/src/ui/button.tsx
import { Frame } from '@nativescript/core'

export const Button = () => {
  function goBack() {
    Frame.goBack()
  }
  return (
    <>
      <actionbar title="Button">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      <gridlayout
        ios:visibility="collapse"
        verticalAlignment="center"
        horizontalAlignment="center"
      >
        {/* #region example */}
        <button on:tap={() => alert('button clicked')}>Click Me</button>
        {/* #endregion example */}
      </gridlayout>
    </>
  )
}

// examples/svelte/app/components/ui/Button.svelte
<script lang="ts">
  import { alert } from '@nativescript/core'
  function showAlert() {
    alert({
      title: 'alert',
      message: "you've made an alert with a click from a button",
      okButtonText: 'OK',
    })
  }
</script>

<page>
  <actionBar>
    <label text="Button" class="font-bold text-lg" />
  </actionBar>
  <gridLayout>
    <contentView verticalAlignment="center">
      <!-- #region example -->
      <button text="this is a button" on:tap={showAlert}></button>
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>
