// examples/react/src/components/ui/datepicker.tsx
import { Dialogs, Frame } from '@nativescript/core'
import { RouteProp } from '@react-navigation/core'
import * as React from 'react'
import { StyleSheet } from 'react-nativescript'
import { FrameNavigationProp } from 'react-nativescript-navigation'

import { MainStackParamList } from '../../NavigationParamList'

type HomeProps = {
  route: RouteProp<MainStackParamList, 'DatePicker'>
  navigation: FrameNavigationProp<MainStackParamList, 'DatePicker'>
}

export function DatePicker({ navigation }: HomeProps) {
  const date = new Date()
  return (
    <>
      <frame>
        <page style={styles.container}>
          <actionBar
            title="DatePicker"
            onTap={() => Frame.goBack()}
          ></actionBar>

          <stackLayout
            verticalAlignment={'middle'}
            horizontalAlignment={'center'}
          >
            {/* #region example */}
            <datePicker date={date}></datePicker>
            {/* #endregion example */}
          </stackLayout>
        </page>
      </frame>
    </>
  )
}

const styles = StyleSheet.create({
  container: {
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  text: {
    textAlignment: 'center',
    fontSize: 24,
    color: 'black',
  },
  button: {
    fontSize: 24,
    color: '#2e6ddf',
  },
})

// examples/svelte/app/components/ui/DatePicker.svelte
<script lang="ts">
  import { Frame } from '@nativescript/core'

  let value = new Date()
  function goBack() {
    Frame.goBack()
  }
</script>

<page>
  <actionBar>
    <label>DatePicker</label>
  </actionBar>

  <gridLayout>
    <contentView horizontalAlignment="center" verticalAlignment="center">
      <stackLayout>
        <!-- #region example -->
        <datepicker bind:date={value}></datepicker>
        <!--  #endregion example -->
        <label>{value}</label>
      </stackLayout>
    </contentView>
  </gridLayout>
</page>

<style>
</style>
