// examples/solidJs/src/ui/datepicker.tsx
import { Frame } from '@nativescript/core'

export const DatePicker = () => {

  const date = new Date(1997, 2,16);
  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="Button">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <datepicker date={date}  ></datepicker>
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};

// examples/svelte/app/components/ui/DatePicker.svelte
<script lang="ts">
  import { Frame } from '@nativescript/core'

  let value = new Date()
  function goBack() {
    Frame.goBack()
  }
</script>

<page>
  <actionBar>
    <label>DatePicker</label>
  </actionBar>

  <gridLayout>
    <contentView horizontalAlignment="center" verticalAlignment="center">
      <stackLayout>
        <!-- #region example -->
        <datepicker bind:date={value}></datepicker>
        <!--  #endregion example -->
        <label>{value}</label>
      </stackLayout>
    </contentView>
  </gridLayout>
</page>

<style>
</style>
