// examples/solid/src/ui/image.tsx
import { Frame } from '@nativescript/core'

export const Image = () => {
  function goBack() {
    Frame.goBack()
  }
  return (
    <>
      <actionbar title="Image">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout
        ios:visibility="collapse"
        verticalAlignment="center"
        horizontalAlignment="center"
      >
        {/* #region example */}
        <image src="~/assets/solid.png" height={60} />
        {/* #endregion example */}
      </gridlayout>
    </>
  )
}

// examples/svelte/app/components/ui/Image.svelte

<page>
    <actionBar >
      <label>Image</label>
    </actionBar>

    <gridLayout>
      <contentView
        horizontalAlignment="center"
        verticalAlignment="center">
<!--      region example -->
        <image src="~/assets/logo.png" height="60"></image>
<!--      endregion example-->
      </contentView>
    </gridLayout>
</page>

<script lang="ts">
</script>

<style>
</style>
