// examples/solidJs/src/ui/listview.tsx
import { Frame } from '@nativescript/core'
export const ListView = () => {
  // #region example
  const items = [];
  for(let index = 0; index < 100; index++) {
    items.push({
      text: `Item ${index+1}`
    })
  }
  // #endregion example
  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="ListView">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout >

        {/*region example todo not working, no direct translation of listview?*/}
        <list-view items={items}>
        </list-view>
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};

// examples/svelte/app/components/ui/ListView.svelte
<!-- #region example -->
<script lang="ts">
  import { Template } from '@nativescript-community/svelte-native/components'

  const items = []
  for (let i = 0; i < 100; i++) {
    items.push({
      title: `Item ${i + 1}`,
    })
  }
</script>

<page>
  <actionBar title="ListView">
  </actionBar>

  <gridLayout>
    <listView {items}>
      <Template let:item>
        <stackLayout>
          <label>{item.title}</label>
        </stackLayout>
      </Template>
    </listView>
  </gridLayout>
</page>
<!-- #endregion example -->
<style>
</style>
