// examples/solid/src/ui/progress.tsx
{/* #region example */}
import { createSignal } from 'solid-js'

export const Progress = () => {
  const [count, setCount] = createSignal(0)
  setInterval(() => {
    setCount(count() + 1)
    if (count() === 101) setCount(0)
  }, 100)
  return (
    <>
      <actionbar title="Progress">
      </actionbar>
      <gridlayout>
        <progress value={count()}></progress>
      </gridlayout>
    </>
  )
}
{/* #endregion example */}

// examples/svelte/app/components/ui/Progress.svelte
<!-- #region example -->
<script lang="ts">
  let currentValue = 0
  setInterval(() => {
    currentValue++
    if (currentValue === 101) currentValue = 0
  }, 100)
</script>

<page>
  <actionBar title="Progress">
  </actionBar>

  <gridLayout width="100%">
    <progress bind:value={currentValue}></progress>
  </gridLayout>
</page>
<!-- #endregion example -->

<style>
</style>
