// examples/solidJs/src/ui/searchbar.tsx
import { Frame } from '@nativescript/core'

export const SearchBar = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="SearchBar">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <searchbar hint="SEARCH HERE"></searchbar>
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};

// examples/svelte/app/components/ui/SearchBar.svelte

<page>
    <actionBar >
      <label>SearchBar </label>
    </actionBar>

  <gridLayout width="100%">
    <contentView
      width="100%"
      horizontalAlignment="center"
      verticalAlignment="center">
      <!--      region example -->
      <searchBar hint="SEARCH HERE"></searchBar>
      <!--      endregion example-->
    </contentView>
  </gridLayout>
</page>

<script lang="ts">
</script>

<style>
</style>
