// examples/solidJs/src/ui/segmentedbar.tsx
import { Frame } from '@nativescript/core'

export const SegmentedBar = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="SegmentedBar">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <segmentedbar>
          <segmentedbaritem title="First" />
          <segmentedbaritem title="Second" />
          <segmentedbaritem title="Third" />
        </segmentedbar>
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};

// examples/svelte/app/components/ui/SegmentedBar.svelte

<page>
    <actionBar >
      <label>SegmentedBar</label>
    </actionBar>

  <gridLayout width="100%">
    <contentView
      width="100%"
      horizontalAlignment="center"
      verticalAlignment="center">
      <!--      region example -->
      <segmentedBar>
        <segmentedBarItem title="First" />
        <segmentedBarItem title="Second" />
        <segmentedBarItem title="Third" />
      </segmentedBar>
      <!--      endregion example-->
    </contentView>
  </gridLayout>
</page>

<script lang="ts">
</script>

<style>
</style>
