// examples/solid/src/ui/slider.tsx
import { Frame } from '@nativescript/core'
import { createSignal } from 'solid-js'

export const Slider = () => {
  const [sliderValue, setSliderValue] = createSignal(0)
  function goBack() {
    Frame.goBack()
  }

  const handleChange = (event: Event) => {
    setSliderValue(event.value)
    console.log(event.value)
    // You can perform any other actions here based on the updated value
  }

  return (
    <>
      <actionbar title="Slider">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout
        ios:visibility="collapse"
        verticalAlignment="center"
        horizontalAlignment="center"
      >
        <stacklayout>
          {/* #region example */}
          <slider
            width={300}
            value={sliderValue()}
            on:valueChange={handleChange}
          />
          {/* #endregion example */}
          <label>{sliderValue()}</label>
        </stacklayout>
      </gridlayout>
    </>
  )
}

// examples/svelte/app/components/ui/Slider.svelte
<script lang="ts">
  let sliderValue = 0
</script>

<page>
  <actionBar>
    <label>Slider</label>
  </actionBar>

  <gridLayout width="100%">
    <contentView
      width="100%"
      horizontalAlignment="center"
      verticalAlignment="center"
    >
      <stackLayout>
        <!-- #region example -->
        <slider bind:value={sliderValue} />
        <!-- #endregion example -->
        <label width="100%" textAlignment="center">{sliderValue}</label>
      </stackLayout>
    </contentView>
  </gridLayout>
</page>

<style>
</style>
