// examples/solid/src/ui/tabview.tsx
import { Frame } from '@nativescript/core'

export const TabView = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="TabView">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <tabview>
          <tabviewitem title="First">
            <label text="First Tab Content" textAlignment="center" verticalAlignment="center"></label>
          </tabviewitem>
          <tabviewitem title="Second">
            <label text="Second Tab Content" textAlignment="center" verticalAlignment="center"></label>
          </tabviewitem>
          <tabviewitem title="Third">
            <label text="Third Tab Content" textAlignment="center" verticalAlignment="center"></label>
          </tabviewitem>
        </tabview>
        {/*#endregion example*/}

      </gridlayout>
    </>
  );
};

// examples/svelte/app/components/ui/TabView.svelte

<page>
    <actionBar >
      <label>TabView</label>
    </actionBar>

  <gridLayout width="100%">
    <!-- #region example -->
    <tabView>
      <tabViewItem title="First">
        <label text="First Tab Content" textAlignment="center" verticalAlignment="center"></label>
      </tabViewItem>
      <tabViewItem title="Second">
        <label text="Second Tab Content" textAlignment="center" verticalAlignment="center"></label>
      </tabViewItem>
      <tabViewItem title="Third">
        <label text="Third Tab Content" textAlignment="center" verticalAlignment="center"></label>
      </tabViewItem>
    </tabView>
    <!-- #endregion example -->
  </gridLayout>
</page>

<script lang="ts">
</script>

<style>
</style>
