// examples/solid/src/ui/textfield.tsx
import { Frame } from '@nativescript/core'

export const TextField = () => {
  function goBack() {
    Frame.goBack()
  }
  return (
    <>
      <actionbar title="TextField">
        <actionitem on:tap={goBack} text="<<Back"></actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout
        ios:visibility="collapse"
        verticalAlignment="center"
        horizontalAlignment="center"
      >
        {/* #region example */}
        <textfield hint="Placeholder..." />
        {/* #endregion example */}
      </gridlayout>
    </>
  )
}

// examples/svelte/app/components/ui/TextField.svelte
<script lang="ts">
</script>

<page>
  <actionBar>
    <label>TextField</label>
  </actionBar>

  <gridLayout width="100%">
    <contentView verticalAlignment="center">
      <!-- #region example -->
      <textField hint="Placeholder..." />
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>
