// examples/solidJs/src/ui/webview.tsx
import { Frame } from '@nativescript/core'

export const WebView = () => {

  function goBack() {
    Frame.goBack();

  }  return (
    <>
      <actionbar title="WebView">
        <actionitem on:tap={goBack} text='<<Back'>
        </actionitem>
      </actionbar>
      {/* @ts-ignore */}
      <gridlayout ios:visibility="collapse" verticalAlignment="center" horizontalAlignment="center">

        {/*region example*/}
        <activityindicator busy="true" />
        <webview src="https://nativescript.org/" />
        {/*endregion example*/}

      </gridlayout>
    </>
  );
};

// examples/svelte/app/components/ui/WebView.svelte
<script lang="ts">
</script>

<page>
  <actionBar>
    <label>WebView</label>
  </actionBar>

  <gridLayout>
    <!-- keeps the screen busy for Maestro to wait for the WebView... -->
    <activityIndicator busy="true" />
    <webView src="https://nativescript.org/" backgroundColor="transparent" />

    <!-- actual example - not rendered because the above WebView is used for the screenshot instead. -->
    <contentView visibility="collapse">
      <!-- #region example -->
      <webView src="https://nativescript.org/" />
      <!-- #endregion example -->
    </contentView>
  </gridLayout>
</page>

<style>
</style>
